project_name: go-kev
release:
  github:
    owner: vulsio
    name: go-kev
env:
  - CGO_ENABLED=0
builds:
- id: go-kev
  goos:
    - linux
    - windows
  goarch:
    - amd64
    - arm64
  main: .
  ldflags: -s -w -X github.com/vulsio/go-kev/config.Version={{.Version}} -X github.com/vulsio/go-kev/config.Revision={{.Commit}}
  binary: go-kev
archives:
- name_template: '{{ .Binary }}_{{.Version}}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  format: tar.gz
  files:
  - LICENSE
  - README*
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
